"""
56 task di Software Engineering dal dataset di Treude et al.
Stesso elenco usato da Sami et al. e d'Aloisio et al.
"""

TASKS = [
    "accepts changes",
    "archives code versions",
    "asks coworkers",
    "assesses potential problems",
    "assigns GitHub issues",
    "browses articles",
    "browses documentation",
    "browses FAQs",
    "browses the web",
    "classifies requirements",
    "codes",
    "commits code",
    "edits artifacts",
    "edits code",
    "elicits requirements",
    "estimates tasks/projects",
    "fixes bugs",
    "fixes defects",
    "generates reports/documents",
    "has meetings",
    "helps others",
    "identifies constraints",
    "inspects code",
    "manages development branches",
    "navigates code",
    "performs administrative tasks",
    "performs personal debugging",
    "performs user training",
    "produces on-line help",
    "produces tutorials",
    "produces user documentation",
    "provides comments on commits",
    "provides comments on issues",
    "provides comments on project milestones",
    "provides enhancements",
    "reads artifacts",
    "reads changes",
    "reads/reviews code",
    "releases code versions",
    "removes dead code",
    "restructures code",
    "reviews pull requests",
    "stores design versions",
    "submits changes",
    "submits pull requests",
    "tests",
    "writes artifacts",
    "writes documentation/wiki pages",
    "writes emails",
    "learns",
    "maintains changes",
    "mentors others",
    "networks",
    "performs infrastructure setup",
    "performs support tasks",
    "plans",
]

assert len(TASKS) == 56, f"Expected 56 tasks, got {len(TASKS)}"
